# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ruby Wood MMath
title: Health Data Science DPhil Student
email: ruby.wood@eng.ox.ac.uk
website: rubywood.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  rubywood
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: rubywood
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000−0001−9916−888X

# Additional icon links
additional_links:
- title: Ruby Wood BDI
  icon: fas fa-user
  url: https://www.bdi.ox.ac.uk/Team/ruby-wood
- title: Ruby Wood OxWoCS
  icon: fas fa-venus
  url: https://www.oxwocs.com/team
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
# TODO: add CV link that shows pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/RWProfile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Ruby, a Health Data Science CDT DPhil student at the University of Oxford. I am currently working in the Quantitative Biomedical Imaging research group, using deep learning imaging techniques to predict how a cancer patient will respond to treatment. My research is funded by Cancer Research UK.
  
  I am also a big advocate for women in STEM, and am passionate about improving the representation of women in our fields. This year I am the Vice President of Oxford Wom*n in Computer Science, and am an ongoing instructor for Code First Girls, a charity that teaches women how to code.

  I am most skilled in: <mark>Deep Learning</mark> and coding (<mark>Python</mark>, <mark>Java</mark>).

content:
  - title: PhD # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Predicting a colorectal cancer patient's response to radiotherapy using deep learning techniques
        # link: https://eng.ox.ac.uk/people/ruby-wood/
        caption: | # 
          <a href="https://eng.ox.ac.uk/people/ruby-wood/" target="_blank"><img src="images/oxenglogo.png" alt="Oxford Engineering Profile" style="width:20%;height:20%;"></a>
        # TODO: chnage image size relative and open link in new tab
        #additional_links:
        #  - title:  Oxford Engineering Profile
        #    icon: 
        #    url: https://eng.ox.ac.uk/people/ruby-wood/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: 
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          My PhD researches state of the art deep learning techniques in order to apply these in a medical setting. I am currently trying to predict a colocrectal cancer patient's response to radiotherapy from digital histology slides taken from tissue biopsies. To do this, I am developing techniques to enhance the context of the histology images, using the tissue morphology to aid predictions. I am exploring ways in which we can make such predictions more interpretable to clinicians, in order to move towards clinical translation of such a deep learning model.


  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Enhancing Local Context of Histology Features in Vision Transformers
        link: https://link.springer.com/chapter/10.1007/978-3-031-19660-7_15
        link_text: Paper Link
        sub_title: Ruby Wood, Korsuk Sirinukunwattana, Enric Domingo, Alexander Sauer, Maxime W Lafarge, Viktor H Koelzer, Timothy S Maughan and Jens Rittscher 
        caption: MICCAI MIABID Workshop 2022
        description: | # this will include new lines to allow paragraphs
          Predicting complete response to radiotherapy in rectal cancer patients using deep learning approaches from morphological features extracted from histology biopsies provides a quick, low-cost and effective way to assist clinical decision making. We propose adjustments to the Vision Transformer (ViT) network to improve the utilisation of contextual information present in whole slide images (WSIs). Firstly, our position restoration embedding (PRE) preserves the spatial relationship between tissue patches, using their original positions on a WSI. Secondly, a clustering analysis of extracted tissue features explores morphological motifs which capture fundamental biological processes found in the tumour micro-environment. This is introduced into the ViT network in the form of a cluster label token, helping the model to differentiate between tissue types. The proposed methods are demonstrated on two large independent rectal cancer datasets of patients selectively treated with radiotherapy and capecitabine in two UK clinical trials. Experiments demonstrate that both models, PREViT and ClusterViT, show improvements in the prediction over baseline models.
        border: weak
      - layout: top-middle
        title: Predicting Molecular Traits from Tissue Morphology Through Self-interactive Multi-instance Learning
        link: https://link.springer.com/chapter/10.1007/978-3-031-16434-7_13
        link_text: Paper Link
        sub_title: Yang Hu, Korsuk Sirinukunwattana, Kezia Gaitskell, Ruby Wood, Clare Verrill and Jens Rittscher
        caption: MICCAI 2022
        description: | # this will include new lines to allow paragraphs
          Previous efforts to learn histology features that correlate with specific genetic/molecular traits resort to tile-level multi-instance learning (MIL) which relies on a fixed pretrained model for feature extraction and an instance-bag classifier. We argue that such a two-step approach is not optimal at capturing both fine-grained features at tile level and global features at slide level optimal to the task. We propose a self-interactive MIL that iteratively feedbacks training information between the fine-grained and global context features. We validate the proposed approach on 4 subtyping tasks: EMT status (ovarian), KRAS mutation (colon and lung), EGFR mutation (colon), and HER2 status (breast). Our approach yields an average improvement of 7.05%−8.34% (in terms of AUC) over the baseline.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: JPMorgan
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: 2018 - 2020
        quote: >
          JPMorgan is a financial institution and one of the world's biggest technology driven companies.
        description: | # this will include new lines to allow paragraphs
          Trained as a software engineer, learning software development in Java and other languages such as Angular, JavaScript and HTML. Within my permanent role I developed applications in Java with Spring, and developed machine learning solutions with AWS SageMaker and other AWS services.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of St Andrews
        caption: 2014 - 2018
        sub_title: MMath Mathematics
        quote: >
          The University of St Andrews ranks 1st in the 2023 Guardian University Guide league table overall, and 2nd for Mathematics.
        description: | # this will include new lines to allow paragraphs
          Received a First Class integrated Masters of Mathematics degree, with a focus on statistics. My MMath dissertation, 'Comparing Classical Clustering Approaches with Bayesian Partitioning', won the University of St Andrews Duncan Prize for performance in Statistics in Senior Honours Year.

  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #    - Rock climbing
  #    - Gaming
  #    - Knitting
  #    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #    Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
